version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/pr_groceries_db
      SPRING_DATASOURCE_PASSWORD: pass
  mysqldb:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pr_groceries_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql